language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "6"
  - "8"
  - "node"

install:
  - npm install

notifications:
  email: false
